apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# wskazujemy bazę
resources:
  - ../../base

namespace: memory-game

# przyrostek dla produkcji (np. memory-backend-prod)
nameSuffix: -prod

configMapGenerator:
  - name: memory-game-config
    behavior: merge
    literals:
      - NODE_ENV=production