apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Wskazujemy bazę
resources:
  - ../../base

# Przestrzeń nazw dla produkcji
namespace: memory-game

# Przyrostek dla produkcji (np. memory-backend-prod)
nameSuffix: -prod

configMapGenerator:
  - name: memory-game-config
    behavior: merge
    literals:
      - NODE_ENV=production