apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-backend
  namespace: memory-game
  labels:
    app: memory-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: memory-backend
  template:
    metadata:
      labels:
        app: memory-backend
    spec:
      containers:
        - name: backend-container
          image: memory-backend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
