apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-frontend
  namespace: memory-game
  labels:
    app: memory-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-frontend
  template:
    metadata:
      labels:
        app: memory-frontend
    spec:
      containers:
        - name: frontend-container
          image: memory-frontend:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"