name: CI/CD Pipeline - Memory Game

on:
  push:
    branches: [ main ]

jobs:
  build-publish-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # logowanie do darmowego rejestru obrazów na GitHubie (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # budowanie obrazów i publikacja do rejestru
      - name: Build and Push Backend Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/memory-backend:latest

      - name: Build and Push Frontend Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/memory-frontend:latest

      # budowanie obrazów lokalnie do testów klastra
      - name: Build local images for testing
        run: |
          docker build -t memory-backend:latest ./backend
          docker build -t memory-frontend:latest ./frontend

      # uruchomienie klastra testowego Kind
      - name: Create Kubernetes local cluster (Kind)
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind-cluster

      # ładowanie obrazów bezpośrednio do klastra (nie będzie ich szukał w sieci)
      - name: Load images into Kind
        run: |
          kind load docker-image memory-backend:latest --name kind-cluster
          kind load docker-image memory-frontend:latest --name kind-cluster

      # stworzenie przestrzeni nazw i wdrożenie aplikacji
      - name: Create Namespace and Deploy
        run: |
          kubectl create namespace memory-game
          kubectl apply -k k8s/overlays/dev

      # test wdrożenia rollout
      - name: Verify Backend Rollout Status
        run: |
          kubectl rollout status deployment/memory-backend-dev -n memory-game --timeout=90s